export const searchResultsConstants = {
    SEARCH_CONTENT: 'SEARCH_CONTENT',
    UPDATE_CONTENT: 'UPDATE_CONTENT',
    IS_LOADING: 'IS_LOADING',
    FILTER_CONTENT: 'FILTER_CONTENT',
    UPDATE_OFFSET: 'UPDATE_OFFSET',
    UPDATE_FILTER: 'UPDATE_FILTER',
    UPDATE_LOADING_CONTENT: 'UPDATE_LOADING_CONTENT',
    RESET_OFFSET: 'RESET_OFFSET',
    INITIAL_LOAD_FILTER_CONTENT: 'INITIAL_LOAD_FILTER_CONTENT',
    UPDATE_HAS_MORE: 'UPDATE_HAS_MORE',
    RESET_VALUES: 'RESET_VALUES',
    SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
    CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE',
  };
  